apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mongo-k8s-stack
  annotations:
    github.com/project-slug: murafay/mongo-k8s-stack
spec:
  type: other
  lifecycle: experimental
  owner: platform
